use new_world;
SELECT name FROM city WHERE population > 8000000;
SELECT name FROM country WHERE name LIKE '%land%';
SELECT name FROM city  WHERE population >= 500000 AND population <= 1000000;
SELECT name FROM country WHERE continent ='Europe';
SELECT name,surfaceArea FROM country  ORDER BY surfaceArea DESC;
SELECT city.name  FROM city    INNER JOIN    country  ON city.countrycode = country.code where country.name ='Netherlands' ;
SELECT population FROM city WHERE name = 'Rotterdam';
SELECT name,surfacearea FROM country GROUP BY name ORDER BY surfacearea DESC  LIMIT 10;
SELECT name, population FROM city GROUP BY name ORDER BY population DESC  LIMIT 10;
SELECT SUM(population)  FROM city;      